### ISSUE TITLE
composeWith local sub generator causes EventEmitter leak

### ISSUE THREAD

**Issue by Freyert** [yeoman/generator#778] opened 2015-03-25 20:06 UTC
I'm using `generator-generator` and you can reproduce this easily with the instructions below.

Scaffold out an application using `yo generator`.
Add a sub-generator using `yo generator:subgenerator x`

In `app/index.js` add ...
```javascript
writing: {
  sub: function () {
    this.composeWith('gen:x', {});
  }
}
```

Now, after reading the docs more closely I understand I needed to add `settings.local` to the composition in order for it to work. Previously this threw a warning about the EventEmitter and just timed out no matter what version of Node I was using.

```
(node) warning: possible EventEmitter memory leak detected. 11 end listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Queue.addListener (events.js:179:15)
    at Queue.once (events.js:204:8)
    at run (/Users/f/Desktop/generator/node_modules/yeoman-generator/lib/base.js:381:20)
    at composeWith (/Users/f/Desktop/generator/node_modules/yeoman-generator/lib/base.js:590:15)
    at module.exports.yeoman.generators.Base.extend.writing.models (/Users/f/Desktop/generator/app/index.js:39:12)
    at /Users/f/Desktop/generator/node_modules/yeoman-generator/lib/base.js:409:16
    at processImmediate [as _immediateCallback] (timers.js:358:17)
(node) warning: possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at addListener (events.js:179:15)
    at run (/Users/f/Desktop/generator/node_modules/yeoman-generator/lib/base.js:445:21)
    at composeWith (/Users/f/Desktop/generator/node_modules/yeoman-generator/lib/base.js:590:15)
    at module.exports.yeoman.generators.Base.extend.writing.models (/Users/f/Desktop/generator/app/index.js:39:12)
    at /Users/f/Desktop/generator/node_modules/yeoman-generator/lib/base.js:409:16
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

**Comment by SBoudrias** [comment] 2015-03-25 20:12
What version? Which command did you run? Is it still happening using `settings.local`?

If you can provide code exposing this behavior in a github repo I can clone, that'll help too.

**Comment by Freyert** [comment] 2015-03-25 21:25
I'm running ...
```
yo v1.4.6
node: v0.12.0 & v0.10.28
```
Just run `npm test`
https://github.com/Freyert/LeakyGenerator

**Comment by SBoudrias** [comment] 2015-03-27 07:13
I get a feeling this might be related to node 0.12

I'm running 0.10 locally and the generator throw an error about not finding the composed generator.

**Comment by Freyert** [comment] 2015-03-27 17:41
Mac, and I ran it with 0.10 and 0.12

**Comment by olsonpm** [comment] 2015-04-21 02:57
For future readers: I was running into this on v0.10.36, but not when I updated to v0.12.2 it no longer appeared.  I did not spend time to look into why.

**Comment by addyosmani** [comment] 2015-05-03 17:39
@olsponpm were you on Windows when you verified the issue against 0.12.2?

**Comment by olsonpm** [comment] 2015-05-03 19:12
Ubuntu 14.10

**Comment by SBoudrias** [comment] 2015-05-07 01:40
Without further details to reproduce, I'll close the issue. We can't do anything about it until we have a to correctly reproduce it.

**Comment by olsonpm** [comment] 2015-05-31 02:12
One way I was able to reproduce this is by having 10 composeWith statements.  Makes sense though, assuming each one creates an event listener.

https://github.com/olsonpm/composewith-eventemitter-leak/tree/master

**Comment by pebanfield** [comment] 2015-07-08 20:00
I've just reproduced with the following steps - 

1. npm install --global generator-node
2. mkdir test && cd test && yo node
3. there are quite a few options and it has failed twice now like this - 

➜  generator-node  yo node
? Module Name: generator-node

? The name above already exists on npm, choose another? Yes
? Module Name: generator-nodegit-adapter
? Description:
? Project homepage url:
? GitHub username or organization:
? Author's Name: Peter Emonds-Banfield
? Author's Email: pebanfield@gmail.com
? Author's Homepage:
? Key your keywords (comma to split)
? Send coverage reports to coveralls: Yes
(node) warning: possible EventEmitter memory leak detected. 11 end listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Queue.addListener (events.js:179:15)
    at Queue.once (events.js:204:8)
    at run (/usr/local/lib/node_modules/generator-node/node_modules/yeoman-generator/lib/base.js:396:20)
    at composeWith (/usr/local/lib/node_modules/generator-node/node_modules/yeoman-generator/lib/base.js:625:15)
    at module.exports.generators.Base.extend [as default] (/usr/local/lib/node_modules/generator-node/generators/app/index.js:235:12)
    at /usr/local/lib/node_modules/generator-node/node_modules/yeoman-generator/lib/base.js:428:16
    at processImmediate [as _immediateCallback] (timers.js:358:17)
(node) warning: possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at addListener (events.js:179:15)
    at run (/usr/local/lib/node_modules/generator-node/node_modules/yeoman-generator/lib/base.js:473:21)
    at composeWith (/usr/local/lib/node_modules/generator-node/node_modules/yeoman-generator/lib/base.js:625:15)
    at module.exports.generators.Base.extend [as default] (/usr/local/lib/node_modules/generator-node/generators/app/index.js:235:12)
    at /usr/local/lib/node_modules/generator-node/node_modules/yeoman-generator/lib/base.js:428:16
    at processImmediate [as _immediateCallback] (timers.js:358:17)
? Your website (optional): ()

Perhaps something about the size of the prompts array? That would fit with olsonpm stress test suggestion. I dunno just a guess - I just started looking at the yeoman api today. 

I am using -  
- Mac Yeosemite
- yeoman 1.4.7
- node v0.12.4

I was also using generator-generator although I don't see the relationship. 

Peter

**Comment by olsonpm** [comment] 2015-07-08 20:32
@peban First of all I think you're misinterpreting the 'Module Name' query.  It's asking you to name the module that you're creating.  Generator-node is meant to generate node modules, not provide the base for another generator.

Also I just checked generator-node and, by default, it will be composed with 10 other generators.  This is what I found in my previous comment.

@SBoudrias - are you able to replicate via either of the above two test cases?

**Comment by SBoudrias** [comment] 2015-07-08 20:34
We probably should set a higher limit on our event emitter. Each composed generator will add a listener for the same events, so we should set an unlimited value here.

**Comment by olsonpm** [comment] 2015-07-08 20:36
Yeah - I don't know enough about eventemitter listeners to give any suggestions, but that will definitely fix the problem.

**Comment by pebanfield** [comment] 2015-07-08 20:41
@olsonpm - yes I do get the module name query now thanks. I am in the middle of trying to figure out how to create a generator using composeWith. 

I would have thought that this would occur only where you have added listeners without removing them - thus leading to the memory leak. However, your module just appears to emit events in that routine rather than add listeners so not sure.

**Comment by olsonpm** [comment] 2015-07-08 20:51
@pebanfield - Yeah you're getting deeper into the code than I've been.  Without looking into it, I just assumed the composed generators each created a listener.  They stick around through the duration of the generation process, so that would explain them not getting removed.  My assumptions aren't worth much though!

Either way, a temporary fix is to set the max listeners inside your generator.  [See here](https://github.com/olsonpm/composewith-eventemitter-leak/blob/master/generator-base/generators/app/index.js#L17-L19) for my test scenario.

Good luck with the learning process. I found yeoman to be very helpful.

**Comment by SBoudrias** [comment] 2015-07-08 20:54
Every composed generator is listening for events on multiple shared resources during the generation process (one obvious one is listening for changes to mem-fs).

These are generating the listeners warnings when you're composing >10 generators.

**Comment by pebanfield** [comment] 2015-07-08 21:17
Hmm yes increasing maxListeners sounds like the pragmatic option since it seems like an edge case. The robust solution may not be worth pursuing. That default sounds really low anyways compared to other runtimes I've worked with. 

But what about catching the warning? The generator does not crash by the way, and seems to work and so the warning is really only affecting the CLI user experience.

**Comment by pebanfield** [comment] 2015-07-08 21:18
Mainly I don't want people using my generator to see a big ugly stack trace since I'm not concerned about perf. Thanks.

**Comment by SBoudrias** [comment] 2015-07-08 21:31
Like I said, we'll fix in the core and release a patch version. You won't have to worry about it.

**Comment by pebanfield** [comment] 2015-07-08 21:52
That's excellent thanks. There's no rush here though.

**Comment by SBoudrias** [comment] 2015-07-09 06:20
Fixed in a patch version of `yeoman-environment`.

This mean this will be fix in contained in `yo`. `npm -g update yo` should fix it.

**Closed** 2015-07-09 06:20 UTC
Labels: actionnable, bug, medium

**Comment by olsonpm** [comment] 2015-07-09 13:34
Thanks much,

Given there may have been multiple causes to this issue, any future users running into this problem should open a new issue with steps on how to reproduce.
