### ISSUE TITLE
This generator (cici:app) requires yeoman-environment at least 3.0.0-beta.1, current version is 2.10.3

### ISSUE THREAD

**Issue by hiciciya** [yeoman/generator#1280] opened 2021-02-22 05:05 UTC
build my own yeoman generator
when the yeoman generator vesion 5.0.0 
cant run and the error is requires yeoman-environment at least 3.0.0-beta.1, current version is 2.10.3

**Comment by mshima** [comment] 2021-02-22 11:38
Duplicate of https://github.com/yeoman/generator/issues/1279

**Closed by mshima** 2021-02-22 11:38 UTC
Labels: needs triage
