### ISSUE TITLE
Clarify what to use instead of installDependencies action

### ISSUE THREAD

**Issue by bgdopus** [yeoman/generator#1303] opened 2021-06-23 08:46 UTC
Since version 5.0.0 the Install action is deprecated and is not included by default to the generator instance. This is currently not documented. So how should we do npm install?
Please provide a clear explanation how and what should we use?

**Comment by mshima** [comment] 2021-06-23 23:55
Duplicate of https://github.com/yeoman/generator/issues/1294.

**Closed by mshima** 2021-06-23 23:55 UTC
Labels: needs triage
