### ISSUE TITLE
Priority does not work as I expected

### ISSUE THREAD

**Issue by Ovski4** [yeoman/generator#839] opened 2015-07-30 09:42 UTC
Hi,

I'm just getting started and trying to build my own generator, but I don't understand how priorities work.

Here is my package.json file

```json
{
  "name": "generator-ovski-custom",
  "version": "0.1.0",
  "description": "",
  "files": [],
  "keywords": [
    "yeoman-generator"
  ],
  "dependencies": {
    "yeoman-generator": "^0.20.2"
  }
}
```

Here is my generators/app/index.js

```js
var generators = require('yeoman-generator');

var myVar = "FIRST";

module.exports = generators.Base.extend({
    end: function () {
        console.log('END');
        console.log(myVar);
    },
    prompting: function () {
        console.log("PROMPTING");
        var done = this.async();
        this.prompt({
            type: 'input',
            name: 'name',
            message: 'Your project name',
            default: this.appname
        }, function (answers) {
            myVar = answers.name;
            this.log(answers.name);
            done();
        }.bind(this));
    },
    init: function () {
        console.log('INIT');
	console.log(myVar);
    }
});
```

I read the docs at http://yeoman.io/authoring/running-context.html so here is what I expected by running yo ovski-custom:

```
INIT
FIRST
PROMPTING
? Your project name: Ok
Ok
END
Ok
```

And here is what i got:

```
END
FIRST
PROMPTING
? Your project name: Ok
Ok
INIT
Ok
```
Maybe I didn't understood, and the "grouped-queue thing" is only triggered if I start composing generators together?
I get the same behaviour with group priorities, and with the version 0.17.7 of the yeoman-generator dependency.

Thanks!

**Comment by SBoudrias** [comment] 2015-07-30 19:58
Try on the latest version.

**Comment by SBoudrias** [comment] 2015-07-30 19:59
Also, `init` is not a valid priority name.

**Comment by Ovski4** [comment] 2015-07-31 08:35
I am already using the latest version (0.20.2)

I edited init to initializing, now I got the following

```
END
FIRST
INIT
FIRST
PROMPTING
? Your project name: Ok
Ok
```

The 'prompting' function is still running after the 'end' function

**Comment by SBoudrias** [comment] 2015-07-31 18:34
Will investigate. My guess is the first task is running right away as it's the first one queued.

**Comment by Ovski4** [comment] 2015-08-01 13:22
Thanks. I think you are right, I'll run more tests

**Comment by juliosampaio** [comment] 2015-08-21 15:52
Hey guys, any clue? I'm facing the same issue here. Is there something wrong with my code?

Here is my ../app/index.js

```javascript
var yeoman = require('yeoman-generator');
var util = require('util');
var chalk = require('chalk');
var prompt = require('./prompting');

var MyIonicGenerator = module.exports = function MyIonicGenerator(args, options) {
  yeoman.generators.Base.apply(this, arguments);
  this.argument('appname', { type: String, required: true, desc: 'The name of the app'});
  prompt.init(this);
};

util.inherits(MyIonicGenerator, yeoman.generators.Base);

MyIonicGenerator.prototype.install = function install() {
  var c = this.config;
  var args = ['start', this.appname];

  args = (c.useStarterTeamplate) ? args.push(c.starterTemplate) : args;
  args = (c.package) ? args.push('-i') : args;
  args = (c.package) ? args.push(c.package) : args;
  args = (c.ionicAppID) ? args.push('--io-app-id') : args;
  args = (c.ionicAppID) ? args.push(c.ionicAppID) : args;
  args = (c.useSass) ? args.push('--sass') : args;

  var ionicCli = this.spawnCommand('ionic', args);

  ionicCli
    .on('error', function (err) {
      this.log(chalk.red(JSON.stringify(err)));
    }.bind(this));
};

MyIonicGenerator.prototype.prompting = function prompting() {
  var done = this.async();
  this.prompt(prompt.questions(), function (answers) {
    this.config = answers;
    done();
  }.bind(this));
};
```

When runing it, the first thing executed is the `install` method, any help?

**Comment by SBoudrias** [comment] 2015-08-21 18:13
Maybe just order the priority in the right order for the time being?

**Comment by Ovski4** [comment] 2015-08-23 10:44
That's what I did for the time being. Even though it's still an issue, I'm using group priorities in the right order and it works as expected

**Comment by luckylooke** [comment] 2015-10-21 12:54
Any progress here? I have issue with end, it is called before initialization or not at all.
yo version 1.4.8

**Comment by SBoudrias** [comment] 2015-10-21 17:44
@luckylooke your issue doesn't look related.

**Comment by luckylooke** [comment] 2015-10-21 18:06
@SBoudrias why? It also depends on position of ```end``` property. If I move it on top, it will be fired before ```initialization```. If I move it down, it will not fire at all. I have feeling that it is caused by same bug.

**Comment by SBoudrias** [comment] 2015-10-21 18:09
@luckylooke okay so you have a part of the answer (why it triggers first). But if it doesn't fire when you move it after, it's because your generator is never ending. My educated guess is you're dead looping the process with some asynchronicity management.

**Comment by luckylooke** [comment] 2015-10-21 18:21
@SBoudrias, Ok, thanks for clues.. I will test some things later on it.

**Comment by SBoudrias** [comment] 2015-11-30 08:33
Fixed in https://github.com/SBoudrias/grouped-queue/releases/tag/v0.3.2

**Closed by SBoudrias** 2015-11-30 08:33 UTC
Labels: bug, medium, ready
