### ISSUE TITLE
function for copy folders

### ISSUE THREAD

**Issue by khaninD** [yeoman/generator#1043] opened 2017-10-21 15:09 UTC
does the generator have a function for copying folders? 
I i use [ncp](https://github.com/AvianFlu/ncp), but in tests: assert.file('src/index.html')  - **Fail**
![image](https://user-images.githubusercontent.com/18055884/31853014-5d838f38-b68a-11e7-88b9-970c5ac183c1.png)
p.s another files such as: src\styles\main.css, src\index.js. copying with this.fs.copy  and test - true ...

**Comment by SBoudrias** [comment] 2017-10-22 01:59
`this.fs.copy` can properly copy all the files in a folder.

If you're talking about empty folders, then the issue is that you won't be able to commit them to git (git only track files). In this case, you'd want to use `mkdirp` to create them on the fly.

**Comment by khaninD** [comment] 2017-10-22 19:03
@SBoudrias, **thanks** for the detailed solution of the problem

**Comment by SBoudrias** [comment] 2017-10-23 02:48
No problems, let me know if this doesn't work out. I'll close the issue as seems you get a fix.

**Closed by SBoudrias** 2017-10-23 02:48 UTC
