### ISSUE TITLE
Run sub-generator in different directory using composeWith()

### ISSUE THREAD

**Issue by alatzl** [yeoman/generator#845] opened 2015-08-06 20:07 UTC
See [this post](http://stackoverflow.com/questions/31862531/yeoman-composewith-change-directory) on StackOverflow for additional context. 

I have a yeoman generator (GenA) that is using a sub-generator (GenB). GenA will create a `public/` folder in my application structure, and I want GenB to run from that folder and place all of its files within `/public` (mostly because I want to be able to install dependencies through Bower in GenB).

Relevant part of GenA:

    prompting: function() {
      this.prompt(prompts, function(ans) {
        this.composeWith('GenB', {
          options: {
            application_name: this.application_name
          }
        },
        {
          local: require.resolve('path/to/GenB')
        });
        done();
      }.bind(this))
    };

Relevant part of GenB:

    this.bowConfig = {
      "directory": "public/bower_components"
    };
    this.fs.writeJSON('.bowerrc', this.bowConfig);

    this.bow = {
      "name": this.name,
      "version": "1.0.0",
      "description": "foo",
      "dependencies": { ... },
      "devDependencies": { ... }
    };
    this.fs.writeJSON('bower.json', this.bow);
    
    // and a little later...
    install: function() {
      this.bowerInstall() // this looks for bower.json in the current directory
      // ...
    }

If I change my settings to that I write to `public/bower.json` instead, then when yeoman calls `this.bowerInstall` it doesn't see my `bower.json` file and therefore doesn't install my dependencies. 

If I try to change the root path for all of GenB, like so:

    constructor: function () {
      generators.Base.apply(this, arguments);
      this.destinationRoot('public/')
    }

then all generated files, including those from parent GenA, are generated based on the altered destinationRoot.

Can an option be added to allow for running subgenerators within a different directory, but *only* that subgenerator; not everything? Or can `destinationRoot()` be altered to specify which generators should be affected (or only alter the generator context its called within as a default)?

**Comment by SBoudrias** [comment] 2015-08-06 20:09
Setting `this.destinationRoot()` is actually changing the CWD (`process.chdir()`). This worked fine with single generators, but it is effectively conflict with composition as it's having a side effect on the whole process, not only the current generator.

**Comment by alatzl** [comment] 2015-08-06 21:38
Perhaps a better question here is not how to change the destinationRoot, but instead how to handle composability when multiple generators that are pulled in with `composeWith()` generate the same file (in my case, `bower.json`). The root of my question, and the real issue here, is how to use multiple generators together when they each have their own bower dependencies. Right now, GenA has a `bower.json` file and so does GenB; currently GenB comes second, and therefore its `bower.json` file wins.

Is there a way to handle conflicts like this currently? Should I maybe skip the bower install, generate the `bower.json` for GenB in a sub-folder, and run the install manually at the end?

**Comment by SBoudrias** [comment] 2015-08-06 21:46
@alatzl Yes, just process the json and extend with the keys you need. For example https://github.com/yeoman/generator-node/blob/master/generators/gulp/index.js#L24-L53

**Comment by alatzl** [comment] 2015-08-07 14:58
Thanks. That seems to serve my purpose. I still think this thread is a relevant issue though; and at the very least, it would help if there were more documentation around issues like this, and handling `bower.json` or `package.json` conflicts amongst generators composed together.

**Comment by eddiemonge** [comment] 2015-12-17 02:32
Marking this as a duplicate of https://github.com/yeoman/generator/issues/872 
If someone disagrees with that, please reopen with additional clarifications or let me know on here and I will if the reason is valid.

**Closed by eddiemonge** 2015-12-17 02:32 UTC
Labels: bug, to-discuss
